apiVersion: v2
name: tns-csi-driver
description: A Helm chart for TrueNAS CSI Driver - providing NFS and NVMe-oF storage for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "v0.0.1"

keywords:
  - storage
  - csi
  - truenas
  - nfs
  - nvmeof

home: https://github.com/fenio/tns-csi
sources:
  - https://github.com/fenio/tns-csi

maintainers:
  - name: TrueNAS CSI Driver Contributors
    url: https://github.com/fenio/tns-csi

icon: https://www.truenas.com/wp-content/uploads/2023/01/TrueNAS_Open_Storage.png
