apiVersion: v2
name: tns-csi-driver
description: A Helm chart for TrueNAS Scale CSI Driver - providing NFS, NVMe-oF, and iSCSI storage for Kubernetes (requires TrueNAS Scale 25.10+)

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.8.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "v0.8.0"

keywords:
  - storage
  - csi
  - truenas
  - nfs
  - nvmeof
  - iscsi

home: https://github.com/fenio/tns-csi
sources:
  - https://github.com/fenio/tns-csi

maintainers:
  - name: Bartosz Fenski
    email: fenio@debian.org
    url: https://github.com/fenio

icon: https://www.truenas.com/wp-content/uploads/2023/01/TrueNAS_Open_Storage.png
