{{- include "tns-csi-driver.validateConfig" . -}}
{{- if not .Values.truenas.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tns-csi-driver.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tns-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.customAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  url: {{ .Values.truenas.url | quote }}
  api-key: {{ .Values.truenas.apiKey | quote }}
{{- end }}
